version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .private/database.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  userapi:
    image: innoshop-user-api:0.0.1-alpha
    ports:
      - '7000:7000'
    env_file:
      - .private/secrets.env
    environment:
      - Database__Host=db
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  
  productapi:
    image: innoshop-product-api:0.0.1-alpha
    ports:
      - '8000:8000'
    env_file:
      - .private/secrets.env
    environment:
      - Database__Host=db
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  website:
    image: innoshop-website:0.0.1-alpha
    ports:
      - '5000:5000'
    restart: unless-stopped
    depends_on:
    - productapi
    - userapi